### ISSUE TITLE
how to specify RBF kernel?

### ISSUE THREAD

**Issue by yitang** [aydindemircioglu/lasvmR#1]
Hi, thanks for writing this package. I wonder what's the correct options for RBF kernel? Is it 'kernel = 1'?

**Comment by aydindemircioglu** [comment]
the options are like this, so for RBF kernel its kernel = 2.
maybe i should add this to the docs.
note also that the package does not support all options.

la SVM

---

Usage: la_svm [options] training_set_file [model_file]
options:
-B file format : files are stored in the following format:
        0 -- libsvm ascii format (default)
        1 -- binary format
        2 -- split file format
-o optimizer: set the type of optimization (default 1)
        0 -- online 
        1 -- online with finishing step 
-t kernel_type : set type of kernel function (default 2)
        0 -- linear: u'_v
        1 -- polynomial: (gamma_u'_v + coef0)^degree
        2 -- radial basis function: exp(-gamma_|u-v|^2)
        3 -- sigmoid: tanh(gamma_u'_v + coef0)
-s selection: set the type of selection strategy (default 0)
        0 -- random 
        1 -- gradient-based 
        2 -- margin-based 
-T termination: set the type of early stopping strategy (default 0)
        0 -- number of iterations 
        1 -- number of SVs 
        2 -- time-based 
-l sample: number of iterations/SVs/seconds to sample for early stopping (default all)
 if a list of numbers is given a model file is saved for each element of the set
-C candidates : set number of candidates to search for selection strategy (default 50)
-d degree : set degree in kernel function (default 3)
-g gamma : set gamma in kernel function (default 1/k)
-r coef0 : set coef0 in kernel function (default 0)
-c cost : set the parameter C of C-SVC  
-m cachesize : set cache memory size in MB (default 256)  
-wi weight: set the parameter C of class i to weight*C (default 1)  
-b bias: use a bias or not i.e. no constraint sum alpha_i y_i =0 (default 1=on)  
-e epsilon : set tolerance of termination criterion (default 0.001)  
-p epochs : number of epochs to train in online setting (default 1)  
-D deltamax : set tolerance for reprocess step, 1000=1 call to reprocess >1000=no calls to reprocess (default 1000)

**Comment by yitang** [comment]
that's great. thanks!
