### ISSUE TITLE
predicted probabalities

### ISSUE THREAD

**Issue by yitang** [aydindemircioglu/lasvmR#2]
Hello again. I wonder what's the easiest way to get the predicted probabilities? The lasvmPredict function return the class outcomes. Does it use p=0.5 as the cut-off? it seems the lasvmPredictWrapper could return the predicted probabilities, but it is an exported method.

Thanks.

**Comment by yitang** [comment]
I had a look on the source code. 

this line, https://github.com/aydindemircioglu/lasvmR/blob/26bb937a5a53198ac259e6eb7ee01c5570ae9209/src/lasvm_wrapper.cpp#L350

says if the predicted y value is large than 0, the prediction is 1, else is -1. I wonder if we should add a argument so that the function can return predicted probabilities? 

Y

**Comment by aydindemircioglu** [comment]
as you have pointed out,
lasvm does not support predicted probabilities. 
you'd need to add additional code to compute them.
the LIBSVM code should have something like this,
so it could be an option to port the corresponding code.
for now i am too busy to do this or add code, sorry, but
if you have an pull request, i'm very happy to add it
to the package.

**Comment by aydindemircioglu** [comment]
thanks a lot, merged it now (but do not have the time to look through ;))
will adapt DESCRIPTION and push it to cran soon.

thanks again!
